name: docker

on:
  push:
    tags:
      - docker-builds-ubuntu-20.04/*

env:
  IMAGE_FQDN: ghcr.io/maldua/zimbra-foss
  DISTRO_VERSION: 20.04

jobs:
  publish-zimbra-foss-builder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split-tag
        run: echo "version=${BRANCH##*/}" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: zimbra-foss-builder Docker image
        run: |
          docker build --tag ${{ env.IMAGE_FQDN }}:docker-ubuntu-${{ env.DISTRO_VERSION }}-${{ steps.split-tag.outputs.version }} . -f Dockerfile-github-ubuntu-20.04
          docker push ${{ env.IMAGE_FQDN }}:docker-ubuntu-${{ env.DISTRO_VERSION }}-${{ steps.split-tag.outputs.version }}
