name: docker

on:
  push:
    tags:
      - docker-builds-rhel-8/*

env:
  IMAGE_FQDN: ghcr.io/maldua/zimbra-foss

jobs:
  publish-zimbra-foss-builder-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - name: RHEL 8
            version: {{VERSION}}
            tag_prefix: docker-builds-rhel-8
            dockerfile: {{DOCKERFILE}}

    name: Build and push Docker for ${{ matrix.distro.name }}
    if: startsWith(github.ref, format('refs/tags/{0}', matrix.distro.tag_prefix))

    steps:
      - uses: actions/checkout@v2

      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split-tag
        run: echo "version=${BRANCH##*/}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: zimbra-foss-builder Docker image
        run: |
          docker build --tag ${{ env.IMAGE_FQDN }}:${{ matrix.distro.name }}-${{ steps.split-tag.outputs.version }} . -f ${{ matrix.distro.dockerfile }}
          docker push ${{ env.IMAGE_FQDN }}:${{ matrix.distro.name }}-${{ steps.split-tag.outputs.version }}
